version: 2

before:
  hooks:
    - templ generate

builds:
  - main: ./cmd/smoothbrain
    binary: smoothbrain
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - formats:
      - tar.gz

checksum:
  name_template: 'checksums.txt'
